%% Generate inequality statistics to be compared with Fortran results

clear;clc;close all
format long g

%% Set folders and flags

% - Directory where txt files generated by Fortran are located:
TxtDir = fullfile('..','output');

%% Load and reshape
% Load data from Fortran
constants = load(fullfile(TxtDir,'constants.txt'));
na        = constants(1); % asset holdings
neps      = constants(2); % labor productivity shock
ntheta    = constants(3); % ability shock
nz        = constants(4); % household type (W,EP,ES,EC,R)
nl        = constants(5); % labor supply grid
nq = 5; %number of quintiles

%Arrays
a_grid      = load(fullfile(TxtDir,'a_grid.txt'));
mu          = load(fullfile(TxtDir,'mu.txt'));

% Distribution
mu = reshape(mu,[na,neps,ntheta,nz]);

%% Given mu, compute marginal distributions
mu_a = zeros(na,1);
for iz=1:nz
    for it=1:ntheta
        for ie=1:neps
            mu_a = mu_a+mu(:,ie,it,iz);
        end
    end
end

%% Inequality statistics
%% NOTE: These are now computed in Fortran. Here I just check that we get the same results

%mu_vec has dim: [na*neps*ntheta*nz,1]
mu_vec = mu(:);

wealth_vec = zeros(na,neps,ntheta,nz);
for iz = 1:nz
    for it = 1:ntheta
        for ie = 1:neps
            for ia = 1:na
                wealth_vec(ia,ie,it,iz) = a_grid(ia);
            end
        end
    end 
end

wealth_vec = wealth_vec(:);
qvec = [0.2,0.4,0.6,0.8]';
% - Method 1: stack wealth and distrib in a long column vector
%             compute gini coefficient and quintiles
[pw, meanw, ~, giniw] = lrzcurve(mu_vec, wealth_vec);

gini_nawid = gini(mu_vec, wealth_vec);


wealth_q = quantili(wealth_vec,mu_vec,qvec);

disp("Method 1 ---------------------------------")
disp("Gini")
disp(giniw)
disp("quintiles")
disp(wealth_q)
disp("---------------------------------------------")
% - Method 2: use a_grid and marginal distrib of wealth
%             compute gini coefficient and quintiles
[pw2, meanw2, ~, giniw2] = lrzcurve(mu_a,a_grid );
wealth_q2 = quantili(a_grid,mu_a,qvec);
gini_nawid2 = gini(a_grid, mu_a);

disp("Method 2 ---------------------------------")
disp("Gini")
disp(giniw2)
disp("quintiles")
disp(wealth_q2)
disp("---------------------------------------------")

% plot(pw(:,1),pw(:,1),'--',pw(:,1),pw(:,2),'linewidth',2)
% legend('perfect equality','Lorenz curve')
% xlim([0 1]),ylim([0 1]),grid on
% xlabel('Share of population')
% ylabel('Share of wealth')
% if do_save==1; print(['results\','fig_lorenz_wealth'],'-dpng'); end

