%% Compute upper bounds for workers and entrepreneurs incomes

clear; clc; close all
format long g

TxtDir = fullfile('..','output','ss_bench');

%% Import data from txt generated by Fortran

constants = load(fullfile(TxtDir,'constants.txt'));
na        = constants(1); % asset holdings
neps      = constants(2); % labor productivity shock
ntheta    = constants(3); % ability shock
nz        = constants(4); % household type (W,EP,ES,EC,R)
no        = constants(5); % occupation (W,EP,ES,EC)

%Arrays
a_grid      = loadArray(fullfile(TxtDir,'a_grid.txt'),[na,1]);
eps_grid    = loadArray(fullfile(TxtDir,'eps_grid.txt'),[neps,1]);
theta_grid  = loadArray(fullfile(TxtDir,'theta_grid.txt'),[ntheta,1]);

%% Set some parameters manually
beta   = 0.92;
r      = 0.02;
w      = 1.27601774261041 ;
delta  = 0.06;
gamma  = 0.475;
vi     = 0.87;
lambda = 2;

%% Max income for worker

eps_max = max(eps_grid);
max_incw = eps_max*w;

%% Grids for capital and labor

n_k = 800;
n_n = 300;
k_grid = linspace(0,100,n_k)';
n_grid = linspace(0,100,n_n)';
theta  = max(theta_grid);

profit_mat = zeros(n_k,n_n);
for n_c = 1:n_n
    for k_c = 1:n_k
        k_val = k_grid(k_c);
        n_val = n_grid(n_c);
        profit_val = fun_profit(theta,k_val,n_val,r,w,delta,gamma,vi);
        profit_mat(k_c,n_c) = profit_val;
    end
end

[max_val,max_ind] = max(profit_mat(:));
[k_ind, n_ind] = ind2sub(size(profit_mat),max_ind);
k_opt = k_grid(k_ind);
n_opt = n_grid(n_ind);
max_val1 = fun_profit(theta,k_opt,n_opt,r,w,delta,gamma,vi);

disp('MAXIMUM INCOME FOR WORKER')
disp(max_incw)
disp('MAXIMUM PROFIT FOR ENTRE')
disp(max_val)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function F = fun_output(theta,k,n,gamma,vi)

inside = k^gamma*n^(1-gamma);
F = theta*inside^vi;

end


function F = fun_profit(theta,k,n,r,w,delta,gamma,vi)


F = fun_output(theta,k,n,gamma,vi)-(r+delta)*k-w*n;

end










