%% Plot shares of entre across LFO by quintiles of income/wealth
% LEGEND
%----------------------- DATA FOLDER -------------------------------------%
% Set data folder "TxtDir" where Matlab reads the data to plot
% The data folder is 'input\name_experiment' where name_experiment refers to
% the scenario (benchmark calibration, no cap on payroll tax etc.)
% Alternatively, the data folder can be '..\output' which is the folder
% where Fortran saves automatically the results. If TxTDir does not exist,
% Matlab will stop.
%----------------------- FIGURE FOLDER -----------------------------------%
% Set the figure folder "FigDir" where Matlab saves the plots. The figure
% folder is 'results\figures\name_experiment' where name_experiment refers to
% the scenario (benchmark calibration, no cap on payroll tax etc.). If
% FigDir does not exist, Matlab will create it.

% Last updated by Alessandro on 2021-05-25
clear;clc;close all
format long g

%% Set folders and flags
% - Flag 0/1 to save figures in PNG format 
do_save = 1;

% - Directory where results are saved as txt (subfolder of input)
ExpNames = ["bench" "no_cap" "inelastic_labor" "a_space_1" "a_space_2" "nl_20" "nl_100" "ntheta_11"];

% bench is benchmark calib
% no cap is payroll tax = tau_p*y, all else the same
% inelastic_labor is chi=0, all else the same

InpDir = "bench";

ExpDir = "bench";

% - Directory where txt files generated by Fortran are located:
TxtDir = fullfile('input',InpDir); 
%TxtDir = fullfile('..','output');

% - Directory where figures are saved
%FigDir = fullfile('results','figures',ExpDir); 
FigDir = fullfile('results','figures',ExpDir); 
% - Check required folders exist
if ~(isfolder(FigDir))
    warning("Figures folder does not exist.. creating it now")
    mkdir(FigDir)
end

%% Load and reshape
% Load data from Fortran

disp("Reading fortran results from")
disp(TxtDir)

constants = load(fullfile(TxtDir,'constants.txt'));
na        = constants(1); % asset holdings
neps      = constants(2); % labor productivity shock
ntheta    = constants(3); % ability shock
nz        = constants(4); % household type (W,EP,ES,EC,R)
nl        = constants(5); % labor supply grid

shares = load(fullfile(TxtDir,'share_entre_quint.txt'));
nq = 5; % number of quintiles

% Reshape
shares = reshape(shares,[nq,nz]);

% Checks
disp("Check shares some to one for each quint:")
check = abs(sum(shares,2)-1);
if any(check>1e-6)
    error("shares do not sum to one")
end

%% Bar plots

disp("Share of total entre for each quint:")
aux = shares(:,2:4);
disp(sum(aux,2))

% First, rescale to eliminate retirees
share_work_entre = zeros(5,4);
% 4 Columns are: work vs sole prop vs Scorp vs Ccorp
for i=1:nq
    share_work_entre(i,1) = shares(i,1)/sum(shares(i,1:4)); % work
    share_work_entre(i,2) = shares(i,2)/sum(shares(i,1:4)); % sole-prop
    share_work_entre(i,3) = shares(i,3)/sum(shares(i,1:4)); % S-corp
    share_work_entre(i,4) = shares(i,4)/sum(shares(i,1:4)); % C-corp
end

share_work_allentre = zeros(5,2);
% 2 Columns are: work vs entre
for i=1:nq
    share_work_allentre(i,1) = share_work_entre(i,1);   % work
    share_work_allentre(i,2) = sum(share_work_entre(i,2:4)); % ALL entre
end

% Choice of the Legal Form conditional on entrepreneurship
% 3 columns: sole prop vs Scorp vs Ccorp
share_lfo = zeros(5,3);
for i=1:nq
    share_lfo(i,1) =  share_work_entre(i,2)/sum(share_work_entre(i,2:4));% sole-prop
    share_lfo(i,2) =  share_work_entre(i,3)/sum(share_work_entre(i,2:4));% S-corp
    share_lfo(i,3) =  share_work_entre(i,4)/sum(share_work_entre(i,2:4));% C-corp
end

% Plot Bar - stacked
% Display one bar for each row of the matrix. 
% The height of each bar is the sum of the elements in the row.
%share_work_entre(2,1) = 1;
figure
h=bar(share_work_entre,'stacked');
title('Occupational choice by wealth')
xlabel('Quintile of Wealth')
ylabel('Shares')
xticks([1 2 3 4 5])
xticklabels({'Q1','Q2','Q3','Q4','Q5'})
set(h, {'DisplayName'}, {'Work','Sole-Prop','S-corp','C-corp'}')
legend('location','best') 
if do_save==1; print(fullfile(FigDir,'barPlot'),'-dpng'); end

%share_work_allentre(2,1) = 1;
figure
h=bar(share_work_allentre,'stacked');
title('Occupational choice by wealth')
xlabel('Quintile of Wealth')
ylabel('Shares')
xticks([1 2 3 4 5])
xticklabels({'Q1','Q2','Q3','Q4','Q5'})
set(h, {'DisplayName'}, {'Work','Entre'}')
legend('location','best') 
if do_save==1; print(fullfile(FigDir,'barPlot_work_entre'),'-dpng'); end

figure
h=bar(share_lfo,'stacked');
title('Choice of the legal form by wealth')
xlabel('Quintile of Wealth')
ylabel('Share of LFO conditional on entrepr.')
xticks([1 2 3 4 5])
xticklabels({'Q1','Q2','Q3','Q4','Q5'})
set(h, {'DisplayName'}, {'Sole-Prop','S-corp','C-corp'}')
legend('location','best') 
if do_save==1; print(fullfile(FigDir,'barPlot_lfo'),'-dpng'); end






