%% Analyze transition results
%% #VC# V25


clear; clc; close all
format long g

% - Directory where txt files generated by Fortran are located:
TxtDir = fullfile('..','output','transition');

% - Directory where figures are saved 
FigDir = fullfile('results','figures'); 

% - Flag 0/1 if want to save plots as png
do_save = 1;

%% Load transition results

T = 100;
% call writedim(KN_path_old,  trim(dir)//trim('KN_path.txt')) 
% call writedim(tr_path_old,  trim(dir)//trim('tr_path.txt'))
% call writedim(agg_path%Y,  trim(dir)//trim('Y_path.txt'))
% call writedim(agg_path%A,  trim(dir)//trim('A_path.txt'))
% call writedim(agg_path%C,  trim(dir)//trim('C_path.txt'))
% 
% call writedim(prices_path%r, trim(dir)//trim('r_path.txt'))
% call writedim(prices_path%w, trim(dir)//trim('wage_path.txt'))

KN_path    = loadArray(fullfile(TxtDir,'KN_path.txt'),[T,1]);
tr_path    = loadArray(fullfile(TxtDir,'tr_path.txt'),[T,1]);
tau_p_path    = loadArray(fullfile(TxtDir,'tau_p_path.txt'),[T,1]);

Y_path    = loadArray(fullfile(TxtDir,'Y_path.txt'),[T,1]);
A_path    = loadArray(fullfile(TxtDir,'A_path.txt'),[T,1]);
C_path    = loadArray(fullfile(TxtDir,'C_path.txt'),[T,1]);
r_path    = loadArray(fullfile(TxtDir,'r_path.txt'),[T,1]);
wage_path    = loadArray(fullfile(TxtDir,'wage_path.txt'),[T,1]);

%% Make plots


figure
plot(1:T,KN_path,'LineWidth',2)
xlabel('Transition periods, t')
title('Capital-Labor ratio in corp. sector')
if do_save==1; print(fullfile(FigDir,'KN_path'),'-dpng'); end

figure
plot(1:T,tr_path,'LineWidth',2)
xlabel('Transition periods, t')
title('Lump-sum transfers')
if do_save==1; print(fullfile(FigDir,'tr_path'),'-dpng'); end

figure
plot(1:T,tau_p_path,'LineWidth',2)
xlabel('Transition periods, t')
title('Payroll tax rate')
if do_save==1; print(fullfile(FigDir,'tau_p_path'),'-dpng'); end


figure
plot(1:T,Y_path(1:T),'LineWidth',2)
xlabel('Transition periods, t')
title('Total output')
if do_save==1; print(fullfile(FigDir,'Y_path'),'-dpng'); end

figure
plot(1:T,A_path(1:T),'LineWidth',2)
xlabel('Transition periods, t')
title('Total capital')
if do_save==1; print(fullfile(FigDir,'A_path'),'-dpng'); end

figure
plot(1:T,C_path(1:T),'LineWidth',2)
xlabel('Transition periods, t')
title('Total consumption')
if do_save==1; print(fullfile(FigDir,'C_path'),'-dpng'); end

figure
plot(1:T,r_path,'LineWidth',2)
xlabel('Transition periods, t')
title('Interest rate')
if do_save==1; print(fullfile(FigDir,'r_path'),'-dpng'); end

figure
plot(1:T,wage_path,'LineWidth',2)
xlabel('Transition periods, t')
title('Wage')
if do_save==1; print(fullfile(FigDir,'wage_path'),'-dpng'); end

