%% Analyze results from fiscal neutral experiments with transitions

clear; clc; close all
format long g

% - Directory where txt files generated by Fortran are located:
TxtDir = fullfile('..','output');

% - Directory where figures are saved 
FigDir = fullfile('results','figures'); 


% - Flag 0/1 if want to save plots as png
do_save = 1;

% Load comparative static results and store them into structures base and
% cf2
base = load_comptran(fullfile(TxtDir,'comptran_fn'));
cf2  = load_comptran(fullfile(TxtDir,'comptran_CF2_fn'));
% Load initial steady state results
ss_base = load_comptran_ss(fullfile(TxtDir,'ss_bench'));
ss_CF2 = load_comptran_ss(fullfile(TxtDir,'CF2_bench'));

%%
fun_plot_comptran(base,cf2,ss_base,ss_CF2, fullfile(FigDir,'comptran_'),do_save)
