%% Analyze Comparative static results

clear; clc; close all
format long g

% - Directory where txt files generated by Fortran are located:
TxtDir = fullfile('..','output');

% - Directory where figures are saved 
FigDir = fullfile('results','figures'); 

% - Flag 0/1 if want to save plots as png
do_save = 1;

% Load comparative static results and store them into structures base and
% cf2
base = load_compstat(fullfile(TxtDir,'compstat'));
%base_fn = load_compstat(fullfile(TxtDir,'compstat_fn'));

cf2  = load_compstat(fullfile(TxtDir,'compstat_CF2'));
%cf2_fn  = load_compstat(fullfile(TxtDir,'compstat_CF2_fn'));

%% Make plots
fun_plot_compstat(base,cf2, fullfile(FigDir,'compstat_'),do_save)

%fun_plot_compstat(base_fn,cf2_fn, fullfile(FigDir,'compstat_fn_'),do_save)



