%% Plot results benchmark steady-state and validation: Model fit and policy functions
% Output figures are saved in the folder output/ss_bench

clear; clc; close all
format long g

% - Directory where txt files generated by Fortran are located:
TxtDir = fullfile('..','output','ss_bench');
InDir = fullfile('..','input');
ValidDir = fullfile('..','output','validation');
% - Directory where figures are saved
FigDir = fullfile('results','figures','ss_bench');
FigValidDir = fullfile('results','figures');

% - Flag 0/1 if want to save plots as png
do_save = 1;

% - Plot options
mylw     = 4;  % line width
myfs   = 18; % font size
mybw = 1;
mybaredge = 3;
myfc1 = [0.06 0.1 0.4]; % facecolor for bar plots
myfc2 = [ 0.5    0.65    0.95];
myfc3 = [0.89 0.92 0.97];
mylc1 = [0 0 0];
mylc2 = [0, 0.4470, 0.7410];
mylc3 = [0.8500, 0.3250, 0.0980];
mylp1 = '-';
mylp2 = '--';
mylp3 = '-.';

% Define color map
% Define the number of colors in the colormap
numColors = 256;
% Define the RGB values for the navy blue colormap
r = linspace(myfc1(1), myfc3(1), numColors);
g = linspace(myfc1(2), myfc3(2), numColors);
b = linspace(myfc1(3), myfc3(3), numColors); % Values for blue channel
% Create the colormap matrix
navyBlueColormap = [r', g', b'];

% - benchmark parameters (need to be the same as input/estim_params.txt)
vi = 0.89;
gamma = 0.475;

%fig_form = '-dpng'; %Options: '-dpng' or '-depsc'

% - Check required folders exist
if ~(isfolder(TxtDir))
    error("Input folder does not exist.. where are the data??")
end
if ~(isfolder(FigDir))
    warning("Figures folder does not exist.. creating it now")
    mkdir(FigDir)
end

%% Load data from txt
%Read txt into Matlab
%Parameters

constants = load(fullfile(TxtDir,'constants.txt'));
na        = constants(1); % asset holdings
neps      = constants(2); % labor productivity shock
ntheta    = constants(3); % ability shock
nz        = constants(4); % household type (W,EP,ES,EC,R)
no        = constants(5); % occupation (W,EP,ES,EC)

%Arrays
a_grid      = loadArray(fullfile(TxtDir,'a_grid.txt'),[na,1]);
eps_grid    = loadArray(fullfile(TxtDir,'eps_grid.txt'),[neps,1]);
theta_grid  = loadArray(fullfile(TxtDir,'theta_grid.txt'),[ntheta,1]);
% Stationary distribution for theta
prob_theta   = loadArray(fullfile(TxtDir,'prob_theta.txt'),[ntheta,1]);  
mu_theta = dot(theta_grid,prob_theta);
sig_theta = std(theta_grid,prob_theta);
% Stationary distribution for epsilon
prob_eps   = loadArray(fullfile(TxtDir,'prob_eps.txt'),[neps,1]);  
mu_eps = dot(eps_grid,prob_eps);
sig_eps = std(eps_grid,prob_eps);


%cash_e = loadArray(fullfile(TxtDir,'cash_e.txt'),[na,ntheta,4]); % used only if o=2,3,4

kpol   = loadArray(fullfile(TxtDir,'kpol.txt'),[na,ntheta,no]);   % used only if o=2,3,4
npol   = loadArray(fullfile(TxtDir,'npol.txt'),[na,ntheta,no]);   % used only if o=2,3,4
phipol = loadArray(fullfile(TxtDir,'phipol.txt'),[na,ntheta,no]); % used only if o=3,4

apoly = loadArray(fullfile(TxtDir,'apoly.txt'),[na,neps,ntheta,no]);
apolr = loadArray(fullfile(TxtDir,'apolr.txt'),[na,1]);

cpoly = loadArray(fullfile(TxtDir,'cpoly.txt'),[na,neps,ntheta,no]);
cpolr = loadArray(fullfile(TxtDir,'cpolr.txt'),[na,1]);

lpoly_w = loadArray(fullfile(TxtDir,'lpoly_w.txt'),[na,neps,ntheta]); %only for workers

%occpol is in [0,1], last dimension o=1,2,3,4
occpol = loadArray(fullfile(TxtDir,'occpol.txt'),[na,neps,ntheta,nz,no]);

Vy = loadArray(fullfile(TxtDir,'Vy.txt'),[na,neps,ntheta,nz]);
Vr = loadArray(fullfile(TxtDir,'Vr.txt'),[na,1]);

% muy: last dimension is the occupation/age in the previous period (z_min)
muy_m = loadArray(fullfile(TxtDir,'muy.txt'),[na,neps,ntheta,nz]);
mur = loadArray(fullfile(TxtDir,'mur.txt'),[na,1]);

% Convert muy such that the last dimension is current occupation
muy = zeros(na,neps,ntheta,no);

for io = 1:no
    for iz_min = 1:nz
        muy(:,:,:,io) = muy(:,:,:,io) + occpol(:,:,:,iz_min,io).*muy_m(:,:,:,iz_min);
    end
end

% Construct array for entrepreneurial output (i.e. business receipts)
entre_output = zeros(na,ntheta,no);
for io = 1:no
    for it = 1:ntheta
        theta_val = theta_grid(it);
        nvec      = npol(:,it,io);
        kvec      = kpol(:,it,io);
        entre_output(:,it,io) = fun_entre_output(theta_val,nvec,kvec,gamma,vi);
    end
end


% Load Moments
model_share_lfo_quint = loadArray(fullfile(TxtDir,'share_lfo_quint.txt'),[3,5]);
model_share_lfo_quint_inc = loadArray(fullfile(TxtDir,'share_lfo_quint_inc.txt'),[3,5]);
model_share_entre_quint = loadArray(fullfile(TxtDir,'share_entre_quint.txt'),[5,1]);
model_share_entre_quint_inc = loadArray(fullfile(TxtDir,'share_entre_quint_inc.txt'),[5,1]);

data_share_lfo_quint = loadArray(fullfile(InDir,'share_lfo_quint.txt'),[3,5]);
data_share_lfo_quint_inc = loadArray(fullfile(InDir,'share_lfo_quint_inc.txt'),[3,5]);
data_share_entre_quint = loadArray(fullfile(InDir,'share_entre_quint.txt'),[5,1]);
data_share_entre_quint_inc = loadArray(fullfile(InDir,'share_entre_quint_inc.txt'),[5,1]);

% Load model validation 
T = 100;
share_entre_path = loadArray(fullfile(ValidDir,'share_entre_path.txt'),[T,4]);
share_entre_path(T,:) = share_entre_path(T-1,:);
labshare_EC_path = loadArray(fullfile(ValidDir,'labshare_EC_path.txt'),[T,1]);
labshare_ES_path = loadArray(fullfile(ValidDir,'labshare_ES_path.txt'),[T,1]);
labshare_corp_path = loadArray(fullfile(ValidDir,'labshare_corp_path.txt'),[T,1]);
labshare_allcorp_path = loadArray(fullfile(ValidDir,'labshare_allcorp_path.txt'),[T,1]);
labshare_EC_path(T) = labshare_EC_path(T-1);
labshare_ES_path(T) = labshare_ES_path(T-1);
labshare_corp_path(T) = labshare_corp_path(T-1);
labshare_allcorp_path(T) = labshare_allcorp_path(T-1);

inc_share_EP_path = loadArray(fullfile(ValidDir,'inc_share_EP_path.txt'),[T,1]);
inc_share_ES_path = loadArray(fullfile(ValidDir,'inc_share_ES_path.txt'),[T,1]);
inc_share_EC_path = loadArray(fullfile(ValidDir,'inc_share_EC_path.txt'),[T,1]);
netinc_share_EP_path = loadArray(fullfile(ValidDir,'netinc_share_EP_path.txt'),[T,1]);
netinc_share_ES_path = loadArray(fullfile(ValidDir,'netinc_share_ES_path.txt'),[T,1]);
netinc_share_EC_path = loadArray(fullfile(ValidDir,'netinc_share_EC_path.txt'),[T,1]);

share_wage_ES_path = loadArray(fullfile(ValidDir,'share_wage_ES_path.txt'),[T,1]);
inc_share_EP_path(T) = inc_share_EP_path(T-1);
inc_share_ES_path(T) = inc_share_ES_path(T-1);
inc_share_EC_path(T) = inc_share_EC_path(T-1);
netinc_share_EP_path(T) = netinc_share_EP_path(T-1);
netinc_share_ES_path(T) = netinc_share_ES_path(T-1);
netinc_share_EC_path(T) = netinc_share_EC_path(T-1);
share_wage_ES_path(T) = share_wage_ES_path(T-1);

trans_mat_path = loadArray(fullfile(ValidDir,'trans_mat_path.txt'),[T,4,4]);
trans_mat_path(T,:,:)=trans_mat_path(T-1,:,:);

share_EC_entre_vec = loadArray(fullfile(ValidDir,'share_EC_entre_vec.txt'),[3,1]);
share_ES_entre_vec = loadArray(fullfile(ValidDir,'share_ES_entre_vec.txt'),[3,1]);
share_EP_entre_vec = loadArray(fullfile(ValidDir,'share_EP_entre_vec.txt'),[3,1]);
labshare_EC_vec = loadArray(fullfile(ValidDir,'labshare_EC_vec.txt'),[3,1]);
labshare_ES_vec = loadArray(fullfile(ValidDir,'labshare_ES_vec.txt'),[3,1]);
labshare_corp_vec = loadArray(fullfile(ValidDir,'labshare_corp_vec.txt'),[3,1]);
labshare_allcorp_vec = loadArray(fullfile(ValidDir,'labshare_allcorp_vec.txt'),[3,1]);

share_wage_ES_vec = loadArray(fullfile(ValidDir,'share_wage_ES_vec.txt'),[3,1]);
inc_share_EP_vec = loadArray(fullfile(ValidDir,'inc_share_EP_vec.txt'),[3,1]);
inc_share_ES_vec = loadArray(fullfile(ValidDir,'inc_share_ES_vec.txt'),[3,1]);
inc_share_EC_vec = loadArray(fullfile(ValidDir,'inc_share_EC_vec.txt'),[3,1]);
netinc_share_EP_vec = loadArray(fullfile(ValidDir,'netinc_share_EP_vec.txt'),[3,1]);
netinc_share_ES_vec = loadArray(fullfile(ValidDir,'netinc_share_ES_vec.txt'),[3,1]);
netinc_share_EC_vec = loadArray(fullfile(ValidDir,'netinc_share_EC_vec.txt'),[3,1]);
trans_mat_vec = loadArray(fullfile(ValidDir,'trans_mat_vec.txt'),[3,4,4]);

% Plot options
iamax = 220;
% Mean theta for S and C corp
repmat_theta = zeros(na,neps,ntheta,no);
for ia = 1:na
    for ie = 1:neps
        for io = 1:no
            repmat_theta(ia,ie,:,io) = theta_grid;
        end
    end
end
mean_theta_ES = sum(repmat_theta(:,:,:,3).*muy(:,:,:,3),'all')/sum(muy(:,:,:,3),'all');
mean_theta_EC = sum(repmat_theta(:,:,:,4).*muy(:,:,:,4),'all')/sum(muy(:,:,:,4),'all');

% Median values for shocks epsilon and theta
theta_low = find(theta_grid>=(mu_theta-0*sig_theta),1);
theta_med = find(theta_grid>=mu_theta+0.5*sig_theta,1);
theta_high = find(theta_grid>=mu_theta+2*sig_theta,1);

theta_ES_low = find(theta_grid>=(mean_theta_ES-1*sig_theta),1);
theta_ES_med = find(theta_grid>=mean_theta_ES+0*sig_theta,1);
theta_ES_high = find(theta_grid>=mean_theta_ES+2*sig_theta,1);

theta_EC_low = find(theta_grid>=(mean_theta_EC-1*sig_theta),1);
theta_EC_med = find(theta_grid>=mean_theta_EC+0*sig_theta,1);
theta_EC_high = find(theta_grid>=mean_theta_EC+2*sig_theta,1);

disp([theta_low,theta_ES_low,theta_EC_low; theta_med,theta_ES_med,theta_EC_med; theta_high,theta_ES_high,theta_EC_high])

eps_low = find(eps_grid>=(mu_eps+0*sig_eps),1);
eps_med = find(eps_grid>=mu_eps+1*sig_eps,1);
eps_high = min(neps,find(eps_grid>=(mu_eps+2*sig_eps),1));

%% Calculate counterfactual phi
repmat_phipol = zeros(na,neps,ntheta,no);
for ie = 1:neps
    repmat_phipol(:,ie,:,:) = phipol;
end

Ephi_ec = sum(repmat_phipol(:,:,:,4).*muy(:,:,:,4),"all")/...
    sum(muy(:,:,:,4),"all");
Ephi_cf_es = sum(repmat_phipol(:,:,:,3).*muy(:,:,:,4),"all")/...
    sum(muy(:,:,:,4),"all");
disp(Ephi_ec)
disp(Ephi_cf_es)

%% Plot model fit

figure
b=bar(1:5,100*[data_share_entre_quint,model_share_entre_quint],mybw,'LineWidth',mybaredge);
b(1).FaceColor = myfc1;
b(2).FaceColor = myfc3;
%b(2).LineWidth = 2;
ax = gca;
ax.FontSize = myfs;
ax.YLim = [0,60];
legend('Data','Model','fontsize',myfs,'location','northwest','numcolumns',2)
xlabel('Wealth quintile','fontsize',myfs)
ylabel('Share of entrepreneurs (%)','fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'share_entre_quint'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'share_entre_quint'),'-depsc'); end

figure
b=bar(1:5,100*[data_share_entre_quint_inc,model_share_entre_quint_inc],mybw,'LineWidth',mybaredge);
b(1).FaceColor = myfc1;
b(2).FaceColor = myfc3;
ax = gca;
ax.FontSize = myfs;
ax.YLim = [0,60];
%legend('Data','Model','fontsize',myfs,'location','best')
xlabel('Income quintile','fontsize',myfs)
ylabel('Share of entrepreneurs (%)','fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'share_entre_quint_inc'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'share_entre_quint_inc'),'-depsc'); end

% LFO share at top income or wealth quintile
%mybw = 0.8;
figure
b=bar(1:3, 100*[data_share_lfo_quint_inc(:,5),model_share_lfo_quint_inc(:,5)], mybw, 'grouped','LineWidth',mybaredge);
b(1).FaceColor = myfc1;
%b(2).FaceColor = myfc2;
b(2).FaceColor = myfc3;
ax = gca;
ax.FontSize = myfs;
ax.YLim = [0,60];
xt = get(gca, 'XTick');
set(gca, 'XTick', xt, 'XTickLabel', {'Sole-prop.' 'S-corp.' 'C-corp.'},'fontsize',myfs)
%legend({'Data', 'Model'},'location','best',...
%    'NumColumns',2,'fontsize',myfs)
ylabel('Share of entrepreneurs','fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'share_lfo_top_quint_inc'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'share_lfo_top_quint_inc'),'-depsc'); end

%mybw = 0.8;
figure
b=bar(1:3, 100*[data_share_lfo_quint(:,5),model_share_lfo_quint(:,5)], mybw, 'grouped','LineWidth',mybaredge);
b(1).FaceColor = myfc1;
b(2).FaceColor = myfc3;
ax = gca;
ax.FontSize = myfs;
ax.YLim = [0,60];
xt = get(gca, 'XTick');
set(gca, 'XTick', xt, 'XTickLabel', {'Sole-prop.' 'S-corp.' 'C-corp.'},'fontsize',myfs)
%legend({'Data', 'Model'},'location','best',...
%    'NumColumns',2,'fontsize',myfs)
ylabel('Share of entrepreneurs','fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'share_lfo_top_quint'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'share_lfo_top_quint'),'-depsc'); end

% LFO share by income quintiles
%mybw = 0.8;
figure
b=bar(1:5, data_share_lfo_quint_inc', mybw, 'stack','LineWidth',mybaredge);
b(1).FaceColor = myfc1;
b(2).FaceColor = myfc2;
b(3).FaceColor = myfc3;
ax = gca;
ax.FontSize = myfs;
xlabel('Income quintile','fontsize',myfs)
ylim tight
ylabel('Share','fontsize',myfs)
legend({'Sole-proprietor', 'S-corp.', 'C-corp.'},'location','southwest',...
    'fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'data_share_lfo_quint_inc'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'data_share_lfo_quint_inc'),'-depsc'); end

figure
b=bar(1:5, model_share_lfo_quint_inc', mybw, 'stack','LineWidth',mybaredge);
b(1).FaceColor = myfc1;
b(2).FaceColor = myfc2;
b(3).FaceColor = myfc3;
ax = gca;
ax.FontSize = myfs;
xlabel('Income quintile','fontsize',myfs)
ylim tight
ylabel('Share','fontsize',myfs)
legend({'Sole-proprietor', 'S-corp.', 'C-corp.'},'location','southwest',...
    'fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'model_share_lfo_quint_inc'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'model_share_lfo_quint_inc'),'-depsc'); end

% LFO share by income quintiles
figure
b=bar(1:5, data_share_lfo_quint', mybw, 'stack','LineWidth',mybaredge);
b(1).FaceColor = myfc1;
b(2).FaceColor = myfc2;
b(3).FaceColor = myfc3;
ax = gca;
ax.FontSize = myfs;
xlabel('Walth quintile','fontsize',myfs)
ylim tight
ylabel('Share','fontsize',myfs)
legend({'Sole-proprietor', 'S-corp.', 'C-corp.'},'location','southwest',...
    'fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'data_share_lfo_quint'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'data_share_lfo_quint'),'-depsc'); end

figure
b=bar(1:5, model_share_lfo_quint', mybw, 'stack','LineWidth',mybaredge);
b(1).FaceColor = myfc1;
b(2).FaceColor = myfc2;
b(3).FaceColor = myfc3;
ax = gca;
ax.FontSize = myfs;
xlabel('Wealth quintile','fontsize',myfs)
ylim tight
ylabel('Share','fontsize',myfs)
legend({'Sole-proprietor', 'S-corp.', 'C-corp.'},'location','southwest',...
    'fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'model_share_lfo_quint'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'model_share_lfo_quint'),'-depsc'); end

%% Plot policy function


% Occupational choice probabilities
%occpol with dim: [na,neps,ntheta,4]

% occpol_prob: is the prabability of being in an occupation given asset,
% eps, and theta.
occpol_prob = muy./sum(muy,4);
figure
t=tiledlayout(2,2,'TileSpacing','Compact');
nexttile
contourf(a_grid(1:iamax),theta_grid,squeeze(occpol_prob(1:iamax,eps_low,:,1))','LineStyle','none')
title('Worker','FontSize',myfs-8)
nexttile
contourf(a_grid(1:iamax),theta_grid,squeeze(occpol_prob(1:iamax,eps_low,:,2))','LineStyle','none')
title('Sole proprietor','FontSize',myfs-8)
nexttile
contourf(a_grid(1:iamax),theta_grid,squeeze(occpol_prob(1:iamax,eps_low,:,3))','LineStyle','none')
title('S-corp.','FontSize',myfs-8)
nexttile
contourf(a_grid(1:iamax),theta_grid,squeeze(occpol_prob(1:iamax,eps_low,:,4))','LineStyle','none')
title('C-corp.','FontSize',myfs-8)
colormap(navyBlueColormap)
cb = colorbar;
cb.Layout.Tile = 'east';
xlabel(t,'Asset, a','fontsize',myfs-6)
ylabel(t,'Entre. ability, \theta','fontsize',myfs-6)
if do_save==1; print(fullfile(FigDir,'occpol_prob'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'occpol_prob'),'-depsc'); end

% Capital choice (kpol)
figure
plot(a_grid(1:iamax),kpol(1:iamax,theta_low,2),mylp1,'LineWidth',mylw,'Color',mylc1)
hold on
plot(a_grid(1:iamax),kpol(1:iamax,theta_low,4),mylp2,'LineWidth',mylw,'Color',mylc2)
%hold on
%plot(a_grid(1:iamax),a_grid(1:iamax),'-k','LineWidth',mylw)
legend('Sole-prop. and S-corp.','C-corp.','fontsize',myfs,'location','best')
ax = gca;
ax.FontSize = myfs;
xlim=([a_grid(1),a_grid(iamax)]);
xlabel('Asset, a','fontsize',myfs)
ylabel('Capital, k','fontsize',myfs)
%title('kpol for sole-prop')
if do_save==1; print(fullfile(FigDir,'kpol'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'kpol'),'-depsc'); end


% Hiring choice (npol)
figure
plot(a_grid(1:iamax),npol(1:iamax,theta_low,2),mylp1,'LineWidth',mylw,'Color',mylc1)
hold on
plot(a_grid(1:iamax),npol(1:iamax,theta_low,4),mylp2,'LineWidth',mylw,'Color',mylc2)
%legend('Sole-proprietor and S-corp.','C-corp.','fontsize',myfs,'location','best')
ax = gca;
ax.FontSize = myfs;
xlim=([a_grid(1),a_grid(iamax)]);
xlabel('Asset, a','fontsize',myfs)
ylabel('Employment, n','fontsize',myfs)
%title('kpol for sole-prop')
if do_save==1; print(fullfile(FigDir,'npol'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'npol'),'-depsc'); end


% Share of income declared as wage (phipol)
% S-corps
figure
plot(a_grid(1:iamax),100*phipol(1:iamax,theta_ES_low,3),mylp1,'linewidth',mylw,'Color',mylc1)
hold on
plot(a_grid(1:iamax),100*phipol(1:iamax,theta_ES_med,3),mylp2,'linewidth',mylw,'Color',mylc2)
hold on
plot(a_grid(1:iamax),100*phipol(1:iamax,theta_ES_high,3),mylp3,'linewidth',mylw,'Color',mylc3)
ax = gca;
ax.FontSize = myfs;
ax.YLim = [-5,100];
%legend('Low \theta','Medium \theta','High \theta','location','best',...
%    'fontsize',myfs)
hold off
ylabel('Share of income declared as wage (%)','fontsize',myfs)
xlabel('Asset,a','fontsize',myfs)
%title('phipol, Share of income declared as wage')
if do_save==1; print(fullfile(FigDir,'phipol_es'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'phipol_es'),'-depsc'); end

% C-corps
figure
plot(a_grid(1:iamax),100*phipol(1:iamax,theta_EC_low,4),mylp1,'linewidth',mylw,'Color',mylc1)
hold on
plot(a_grid(1:iamax),100*phipol(1:iamax,theta_EC_med,4),mylp2,'linewidth',mylw,'Color',mylc2)
hold on
plot(a_grid(1:iamax),100*phipol(1:iamax,theta_EC_high,4),mylp3,'linewidth',mylw,'Color',mylc3)
ax = gca;
ax.FontSize = myfs;
%ax.YLim = [0,35];
legend('Low \theta','Medium \theta','High \theta','location','best',...
    'fontsize',myfs)
hold off
ylabel('Share of income declared as wage (%)','fontsize',myfs)
xlabel('Asset,a','fontsize',myfs)
%title('phipol, Share of income declared as wage')
if do_save==1; print(fullfile(FigDir,'phipol_ec'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'phipol_ec'),'-depsc'); end

% Share of income declared as wage (phipol) as a function of entre. output
% S-corps
figure
plot(entre_output(1:180,theta_low,3),phipol(1:180,theta_low,3),mylp1,'linewidth',mylw,'Color',mylc1)
hold on
plot(entre_output(1:180,theta_med,3),phipol(1:180,theta_med,3),mylp2,'linewidth',mylw,'Color',mylc2)
hold on
plot(entre_output(1:180,theta_high,3),phipol(1:180,theta_high,3),mylp3,'linewidth',mylw,'Color',mylc3)
ax = gca;
ax.FontSize = myfs;
legend('Low \theta','Medium \theta','High \theta','location','best',...
    'fontsize',myfs)
hold off
ylabel('Share of income declared as wage','fontsize',myfs)
xlabel('Business receipt','fontsize',myfs)
%title('phipol, Share of income declared as wage')
if do_save==1; print(fullfile(FigDir,'phipol_es_receipt'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'phipol_es_receipt'),'-depsc'); end

% C-corps
figure
plot(entre_output(1:180,theta_low,4),phipol(1:180,theta_low,4),mylp1,'linewidth',mylw,'Color',mylc1)
hold on
plot(entre_output(1:180,theta_med,4),phipol(1:180,theta_med,4),mylp2,'linewidth',mylw,'Color',mylc2)
hold on
plot(entre_output(1:180,theta_high,4),phipol(1:180,theta_high,4),mylp3,'linewidth',mylw,'Color',mylc3)
ax = gca;
ax.FontSize = myfs;
%legend('Low \theta','Medium \theta','High \theta','location','best',...
%    'fontsize',myfs)
hold off
ylabel('Share of income declared as wage','fontsize',myfs)
xlabel('Business receipt','fontsize',myfs)
%title('phipol, Share of income declared as wage')
if do_save==1; print(fullfile(FigDir,'phipol_ec_receipt'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'phipol_ec_receipt'),'-depsc'); end



%% Plot model validation
Tmax = T;
% Steady state comparison

temp_data = zeros(4:2); 
temp_data(1,:) = [share_EP_entre_vec(3),share_EP_entre_vec(1)];
temp_data(2,:) = [share_ES_entre_vec(3),share_ES_entre_vec(1)];
temp_data(3,:) = [share_EC_entre_vec(3),share_EC_entre_vec(1)];
temp_data(4,:) = [labshare_corp_vec(3),labshare_corp_vec(1)];

figure
b=bar(1:4,temp_data,mybw,'LineWidth',mybaredge);
b(1).FaceColor = myfc1;
%b(2).FaceColor = myfc2;
b(2).FaceColor = myfc3;
ax = gca;
ax.FontSize = myfs;
legend('\tau_h = 0.50','\tau_h = 0.28','fontsize',myfs,'location','best')
xlabel('','fontsize',myfs)
xt = get(gca, 'XTick');
set(gca, 'XTick', xt, 'XTickLabel', {'Sole-prop.' 'S-corp.' 'C-corp.' 'Labor share'},'fontsize',myfs)
ylabel('','fontsize',myfs)
if do_save==1; print(fullfile(FigValidDir,'validation_compstat'),'-dpng'); end
if do_save==1; print(fullfile(FigValidDir,'validation_compstat'),'-depsc'); end
 

% Transition: LFO shares
tvec = 0:Tmax;
tvec = tvec';
figure
plot(tvec,100*[share_EP_entre_vec(3);share_entre_path(1:Tmax,2)],mylp1,'LineWidth',mylw,'Color',mylc1)
hold on
ylabel('Share of entrepreneurs (%)','fontsize',myfs)
yyaxis right
plot(tvec,100*[share_ES_entre_vec(3);share_entre_path(1:Tmax,3)],mylp2,'LineWidth',mylw,'Color',mylc2)
hold on
plot(tvec,100*[share_EC_entre_vec(3);share_entre_path(1:Tmax,4)],mylp3,'LineWidth',mylw,'Color',mylc3)
%hold on
%plot(tvec,[labshare_corp_vec(3);labshare_corp_path],':','LineWidth',mylw+2)
ax = gca;
ax.FontSize = myfs;
ax.YLim = [-2,40];
xlabel('Years','fontsize',myfs)
ylabel('Share of entrepreneurs (%)','fontsize',myfs)
%legend('Sole-prop.','S-corp.','C-corp.','fontsize',myfs,'location','east')
if do_save==1; print(fullfile(FigValidDir,'validation_share_entre_path'),'-dpng'); end
if do_save==1; print(fullfile(FigValidDir,'validation_share_entre_path'),'-depsc'); end

% Transition: gross income shares
tvec = 0:Tmax;
tvec = tvec';
figure
plot(tvec,100*[inc_share_EP_vec(3);inc_share_EP_path(1:Tmax)],mylp1,'LineWidth',mylw,'Color',mylc1)
hold on
plot(tvec,100*[inc_share_ES_vec(3);inc_share_ES_path(1:Tmax)],mylp2,'LineWidth',mylw,'Color',mylc2)
hold on
plot(tvec,100*[inc_share_EC_vec(3);inc_share_EC_path(1:Tmax)],mylp3,'LineWidth',mylw,'Color',mylc3)
ax = gca;
ax.FontSize = myfs;
ax.YLim = [-5,80];
xlabel('Years','fontsize',myfs)
ylabel('Share of total entrepreneurial income (%)','fontsize',myfs)
%legend('Sole-prop.','S-corp.','C-corp.','fontsize',myfs,'location','northeast')
if do_save==1; print(fullfile(FigValidDir,'validation_inc_share_path'),'-dpng'); end
if do_save==1; print(fullfile(FigValidDir,'validation_inc_share_path'),'-depsc'); end

% Transition: net business income shares
tvec = 0:Tmax;
tvec = tvec';
figure
plot(tvec,100*[netinc_share_EP_vec(3);netinc_share_EP_path(1:Tmax)],mylp1,'LineWidth',mylw,'Color',mylc1)
hold on
ylabel('Share of total entrepreneurial net income (%)','fontsize',myfs)
yyaxis right
plot(tvec,100*[netinc_share_ES_vec(3);netinc_share_ES_path(1:Tmax)],mylp2,'LineWidth',mylw,'Color',mylc2)
hold on
plot(tvec,100*[netinc_share_EC_vec(3);netinc_share_EC_path(1:Tmax)],mylp3,'LineWidth',mylw,'Color',mylc3)
ax = gca;
ax.FontSize = myfs;
%ax.YLim = [-5,80];
xlabel('Years','fontsize',myfs)
ylabel('Share of total entrepreneurial net income (%)','fontsize',myfs)
legend('Sole-prop. (left axis)','S-corp. (right axis)','C-corp. (right axis)','fontsize',myfs,'location','best')
if do_save==1; print(fullfile(FigValidDir,'validation_netinc_share_path'),'-dpng'); end
if do_save==1; print(fullfile(FigValidDir,'validation_netinc_share_path'),'-depsc'); end


% Transition: ES wage share
tvec = 0:Tmax;
tvec = tvec';
figure
plot(tvec,100*[share_wage_ES_vec(3);share_wage_ES_path(1:Tmax)],mylp2,'LineWidth',mylw,'Color',mylc2)
ax = gca;
ax.FontSize = myfs;
ax.YLim = [-5,80];
xlabel('Years','fontsize',myfs)
ylabel('Wage share (%)','fontsize',myfs)
%legend('S-corp.','fontsize',myfs,'location','best')
if do_save==1; print(fullfile(FigValidDir,'validation_share_wage_ES_path'),'-dpng'); end
if do_save==1; print(fullfile(FigValidDir,'validation_share_wage_ES_path'),'-depsc'); end


% Transition: labor cost
tvec = 0:Tmax;
tvec = tvec';
figure
plot(tvec,100*[labshare_ES_vec(3);labshare_ES_path(1:Tmax)],mylp2,'LineWidth',mylw,'Color',mylc2)
hold on
plot(tvec,100*[labshare_allcorp_vec(3);labshare_allcorp_path(1:Tmax)],mylp1,'LineWidth',mylw-1,'Color','r')
hold off
ax = gca;
ax.FontSize = myfs;
%ax.YLim = [-5,80];
xlabel('Years','fontsize',myfs)
ylabel('Labor share (%)','fontsize',myfs)
legend('S-corp.','Corporate sector','fontsize',myfs,'location','best')
if do_save==1; print(fullfile(FigValidDir,'validation_labshare_path'),'-dpng'); end
if do_save==1; print(fullfile(FigValidDir,'validation_labshare_path'),'-depsc'); end
