%% Plot results benchmark steady-state: policy functions and model fit

clear; clc; close all
format long g

% - Directory where txt files generated by Fortran are located:
TxtDir = fullfile('..','output','ss_bench');
InDir = fullfile('..','input');

% - Directory where figures are saved
FigDir = fullfile('results','figures','ss_bench');

% - Plot options
mylw     = 2;  % line width
myfs     = 18; % font size
mybw = 1;
do_save = 1;

% - Check required folders exist
if ~(isfolder(TxtDir))
    error("Input folder does not exist.. where are the data??")
end
if ~(isfolder(FigDir))
    warning("Figures folder does not exist.. creating it now")
    mkdir(FigDir)
end

%% Load data from txt
%Read txt into Matlab
%Parameters
constants = load(fullfile(TxtDir,'constants.txt'));
na        = constants(1); % asset holdings
neps      = constants(2); % labor productivity shock
ntheta    = constants(3); % ability shock
nz        = constants(4); % household type (W,EP,ES,EC,R)
no        = constants(5); % occupation (W,EP,ES,EC)
%Arrays
a_grid      = loadArray(fullfile(TxtDir,'a_grid.txt'),[na,1]);
eps_grid    = loadArray(fullfile(TxtDir,'eps_grid.txt'),[neps,1]);
theta_grid  = loadArray(fullfile(TxtDir,'theta_grid.txt'),[ntheta,1]);

% Policy functions
%cash_e = loadArray(fullfile(TxtDir,'cash_e.txt'),[na,ntheta,4]); % used only if o=2,3,4
kpol   = loadArray(fullfile(TxtDir,'kpol.txt'),[na,ntheta,4]);   % used only if o=2,3,4
npol   = loadArray(fullfile(TxtDir,'npol.txt'),[na,ntheta,4]);   % used only if o=2,3,4
phipol = loadArray(fullfile(TxtDir,'phipol.txt'),[na,ntheta,4]); % used only if o=3,4

apoly = loadArray(fullfile(TxtDir,'apoly.txt'),[na,neps,ntheta,4]);
apolr = loadArray(fullfile(TxtDir,'apolr.txt'),[na,1]);

cpoly = loadArray(fullfile(TxtDir,'cpoly.txt'),[na,neps,ntheta,4]);
cpolr = loadArray(fullfile(TxtDir,'cpolr.txt'),[na,1]);

lpoly_w = loadArray(fullfile(TxtDir,'lpoly_w.txt'),[na,neps,ntheta]); %only for workers

%occpol is in [0,1], last dimension o=1,2,3,4
occpol = loadArray(fullfile(TxtDir,'occpol.txt'),[na,neps,ntheta,nz,no]);

Vy = loadArray(fullfile(TxtDir,'Vy.txt'),[na,neps,ntheta,nz]);
Vr = loadArray(fullfile(TxtDir,'Vr.txt'),[na,1]);

% muy: last dimension is the occupation/age in the previous period (z_min)
muy_m = loadArray(fullfile(TxtDir,'muy.txt'),[na,neps,ntheta,nz]);
mur = loadArray(fullfile(TxtDir,'mur.txt'),[na,1]);

% Convert muy such that the last dimension is current occupation
muy = zeros(na,neps,ntheta,no);

for io = 1:no
    for iz_min = 1:nz
        muy(:,:,:,io) = muy(:,:,:,io) + occpol(:,:,:,iz_min,io).*muy_m(:,:,:,iz_min);
    end
end




% Moments
model_share_lfo_quint = loadArray(fullfile(TxtDir,'share_lfo_quint.txt'),[3,5]);
model_share_lfo_quint_inc = loadArray(fullfile(TxtDir,'share_lfo_quint_inc.txt'),[3,5]);
model_share_entre_quint = loadArray(fullfile(TxtDir,'share_entre_quint.txt'),[5,1]);
model_share_entre_quint_inc = loadArray(fullfile(TxtDir,'share_entre_quint_inc.txt'),[5,1]);


data_share_lfo_quint = loadArray(fullfile(InDir,'share_lfo_quint.txt'),[3,5]);
data_share_lfo_quint_inc = loadArray(fullfile(InDir,'share_lfo_quint_inc.txt'),[3,5]);
data_share_entre_quint = loadArray(fullfile(InDir,'share_entre_quint.txt'),[5,1]);
data_share_entre_quint_inc = loadArray(fullfile(InDir,'share_entre_quint_inc.txt'),[5,1]);


%% Plot moments


figure
b=bar(1:5,[data_share_entre_quint,model_share_entre_quint],mybw);
b(2).FaceColor = 'w';
b(2).LineWidth = 2;
ax = gca;
ax.FontSize = myfs;
legend('Data','Model','fontsize',myfs,'location','best')
xlabel('Wealth quintile','fontsize',myfs)
ylabel('Fraction of entrepreneurs','fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'share_entre_quint'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'share_entre_quint'),'-depsc'); end

figure
b=bar(1:5,[data_share_entre_quint_inc,model_share_entre_quint_inc],mybw);
b(2).FaceColor = 'w';
b(2).LineWidth = 2;
ax = gca;
ax.FontSize = myfs;
legend('Data','Model','fontsize',myfs,'location','best')
xlabel('Income quintile','fontsize',myfs)
ylabel('Fraction of entrepreneurs','fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'share_entre_quint_inc'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'share_entre_quint_inc'),'-depsc'); end

% LFO share at top income or wealth quintile
mybw = 0.8;
figure
b=bar(1:2, [data_share_lfo_quint_inc(:,5),model_share_lfo_quint_inc(:,5)]', mybw, 'grouped');
b(2).FaceColor = 'w';
b(2).LineWidth = 2;
ax = gca;
ax.FontSize = myfs;
xt = get(gca, 'XTick');
set(gca, 'XTick', xt, 'XTickLabel', {'Data' 'Model'},'fontsize',myfs)
legend({'Sole-proprietor', 'S-corp.', 'C-corp.'},'location','southoutside',...
    'NumColumns',3,'fontsize',myfs)
ylabel('Share of entrepreneurs','fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'share_lfo_top_quint_inc'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'share_lfo_top_quint_inc'),'-depsc'); end

mybw = 0.8;
figure
b=bar(1:2, [data_share_lfo_quint(:,5),model_share_lfo_quint(:,5)]', mybw, 'grouped');
b(2).FaceColor = 'w';
b(2).LineWidth = 2;
ax = gca;
ax.FontSize = myfs;
xt = get(gca, 'XTick');
set(gca, 'XTick', xt, 'XTickLabel', {'Data' 'Model'},'fontsize',myfs)
legend({'Sole-proprietor', 'S-corp.', 'C-corp.'},'location','southoutside',...
    'NumColumns',3,'fontsize',myfs)
ylabel('Share of entrepreneurs','fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'share_lfo_top_quint'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'share_lfo_top_quint'),'-depsc'); end

% LFO share by income quintiles
mybw = 0.8;
figure
b=bar(1:5, data_share_lfo_quint_inc', mybw, 'stack');
b(2).FaceColor = 'w';
b(2).LineWidth = 1;
ax = gca;
ax.FontSize = myfs;
xlabel('Income quintile','fontsize',myfs)
ylim tight
ylabel('Share','fontsize',myfs)
legend({'Sole-proprietor', 'S-corp.', 'C-corp.'},'location','southwest',...
    'fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'data_share_lfo_quint_inc'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'data_share_lfo_quint_inc'),'-depsc'); end

figure
b=bar(1:5, model_share_lfo_quint_inc', mybw, 'stack');
b(2).FaceColor = 'w';
b(2).LineWidth = 1;
ax = gca;
ax.FontSize = myfs;
xlabel('Income quintile','fontsize',myfs)
ylim tight
ylabel('Share','fontsize',myfs)
legend({'Sole-proprietor', 'S-corp.', 'C-corp.'},'location','southwest',...
    'fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'model_share_lfo_quint_inc'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'model_share_lfo_quint_inc'),'-depsc'); end

% LFO share by income quintiles
mybw = 0.8;
figure
b=bar(1:5, data_share_lfo_quint', mybw, 'stack');
b(2).FaceColor = 'w';
b(2).LineWidth = 1;
ax = gca;
ax.FontSize = myfs;
xlabel('Walth quintile','fontsize',myfs)
ylim tight
ylabel('Share','fontsize',myfs)
legend({'Sole-proprietor', 'S-corp.', 'C-corp.'},'location','southwest',...
    'fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'data_share_lfo_quint'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'data_share_lfo_quint'),'-depsc'); end

figure
b=bar(1:5, model_share_lfo_quint', mybw, 'stack');
b(2).FaceColor = 'w';
b(2).LineWidth = 1;
ax = gca;
ax.FontSize = myfs;
xlabel('Wealth quintile','fontsize',myfs)
ylim tight
ylabel('Share','fontsize',myfs)
legend({'Sole-proprietor', 'S-corp.', 'C-corp.'},'location','southwest',...
    'fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'model_share_lfo_quint'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'model_share_lfo_quint'),'-depsc'); end

%% Plot occupational choice
%occpol with dim: [na,neps,ntheta,4]

occpol_prob = muy./sum(muy,4);
iamax = 250;
e_c = 6;
figure
contourf(a_grid(1:iamax),theta_grid,squeeze(occpol_prob(1:iamax,e_c,:,1))','LineStyle','none')
xlabel('Asset, a','fontsize',14)
ylabel('Entre. ability, \theta','fontsize',14)
title(['Prob. worker, \epsilon = ',num2str(eps_grid(e_c))],'fontsize',14)
colorbar
if do_save==1; print(fullfile(FigDir,'occpol_W'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'occpol_W'),'-depsc'); end
figure
contourf(a_grid(1:iamax),theta_grid,squeeze(occpol_prob(1:iamax,e_c,:,2))','LineStyle','none')
xlabel('Asset, a','fontsize',14)
ylabel('Entre. ability, \theta','fontsize',14)
title(['Prob. Sole Proprietor, \epsilon = ',num2str(eps_grid(e_c))],'fontsize',14)
colorbar
if do_save==1; print(fullfile(FigDir,'occpol_EP'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'occpol_EP'),'-depsc'); end
figure
contourf(a_grid(1:iamax),theta_grid,squeeze(occpol_prob(1:iamax,e_c,:,3))','LineStyle','none')
xlabel('Asset, a','fontsize',14)
ylabel('Entre. ability, \theta','fontsize',14)
title(['Prob. S-Corp., \epsilon = ',num2str(eps_grid(e_c))],'fontsize',14)
colorbar
if do_save==1; print(fullfile(FigDir,'occpol_ES'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'occpol_ES'),'-depsc'); end
figure
contourf(a_grid(1:iamax),theta_grid,squeeze(occpol_prob(1:iamax,e_c,:,4))','LineStyle','none')
xlabel('Asset, a','fontsize',14)
ylabel('Entre. ability, \theta','fontsize',14)
title(['Prob. C-Corp., \epsilon = ',num2str(eps_grid(e_c))],'fontsize',14)
colorbar
if do_save==1; print(fullfile(FigDir,'occpol_EC'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'occpol_EC'),'-depsc'); end

%% Plot phi: share of entrepreneurial income declared as wage
theta_low = ntheta*1/3;
theta_med = ntheta*2/3;
theta_hi = ntheta;
% S-corps
figure
plot(a_grid(1:na*3/5),phipol(1:na*3/5,theta_low,3),'-','linewidth',mylw)
hold on
plot(a_grid(1:na*3/5),phipol(1:na*3/5,theta_med,3),'--','linewidth',mylw)
hold on
plot(a_grid(1:na*3/5),phipol(1:na*3/5,theta_hi,3),'-.','linewidth',mylw)
ax = gca;
ax.FontSize = myfs;
legend('Low \theta','Medium \theta','High \theta','location','best',...
    'fontsize',myfs)
hold off
ylabel('Share of income declared as wage','fontsize',myfs)
xlabel('Asset,a','fontsize',myfs)
%title('phipol, Share of income declared as wage')
if do_save==1; print(fullfile(FigDir,'phipol_es'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'phipol_es'),'-depsc'); end

% C-corps
figure
plot(a_grid(1:na*3/5),phipol(1:na*3/5,theta_low,4),'-','linewidth',mylw)
hold on
plot(a_grid(1:na*3/5),phipol(1:na*3/5,theta_med,4),'--','linewidth',mylw)
hold on
plot(a_grid(1:na*3/5),phipol(1:na*3/5,theta_hi,4),'-.','linewidth',mylw)
ax = gca;
ax.FontSize = myfs;
legend('Low \theta','Medium \theta','High \theta','location','best',...
    'fontsize',myfs)
hold off
ylabel('Share of income declared as wage','fontsize',myfs)
xlabel('Asset,a','fontsize',myfs)
%title('phipol, Share of income declared as wage')
if do_save==1; print(fullfile(FigDir,'phipol_ec'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'phipol_ec'),'-depsc'); end

%% Plot kpol
theta_med = ntheta*2/3;
figure
plot(a_grid(1:na*3/5),kpol(1:na*3/5,theta_med,2),'-','LineWidth',mylw)
hold on
plot(a_grid(1:na*3/5),kpol(1:na*3/5,theta_med,3),'--','LineWidth',mylw)
hold on
plot(a_grid(1:na*3/5),kpol(1:na*3/5,theta_med,4),'-.','LineWidth',mylw)
hold on
plot(a_grid(1:na*3/5),a_grid(1:na*3/5),'-k','LineWidth',mylw-1)
legend('Sole-proprietor','S-corp.','C-corp.','45-deg. line','fontsize',myfs,'location','best')
ax = gca;
ax.FontSize = myfs;
xlabel('Asset, a','fontsize',myfs)
ylabel('Capital, k','fontsize',myfs)
%title('kpol for sole-prop')
if do_save==1; print(fullfile(FigDir,'kpol'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'kpol'),'-depsc'); end

