%% Plot results from no avoidance experiments

clear; clc; close all
format long g

% - Directory where txt files generated by Fortran are located:
TxtDir = fullfile('..','output');

% - Directory where figures are saved 
FigDir = fullfile('results','figures','exp'); 

% - Flag 0/1 if want to save plots as png
do_save = 1;
ub = 10e0; 

% - Plot options
mylw     = 3;  % line width
myfs   = 14; % font size
mybw = 1;
mybaredge = 3;
myfc1 = [0.03 0.05 0.29]; % facecolor for bar plots
myfc3 = [ 0.5    0.75    0.98];
myfc2 = (myfc1+myfc3)/2; % facecolor for bar plots
myfc4 = [0.89 0.92 0.97];
mylc1 = [0 0 0];
mylc2 = [0, 0.4470, 0.7410];
mylc3 = [0.8500, 0.3250, 0.0980];
mylp1 = '-';
mylp2 = '--';
mylp3 = '-.';


% - Check required folders exist
if ~(isfolder(TxtDir))
    error("Input folder does not exist.. where are the data??")
end
if ~(isfolder(FigDir))
    warning("Figures folder does not exist.. creating it now")
    mkdir(FigDir)
end

% Number of wealth bins
nq = 4;
%% Read txt into Matlab

% Load CEV data from txt 

exp1.cev_qo = 100*loadArray(fullfile(TxtDir,'exp1_fn','cev_qo.txt'),[nq,2]);
exp2.cev_qo = 100*loadArray(fullfile(TxtDir,'exp2_fn','cev_qo.txt'),[nq,2]);
exp3.cev_qo = 100*loadArray(fullfile(TxtDir,'exp3_fn','cev_qo.txt'),[nq,2]);
exp4.cev_qo = 100*loadArray(fullfile(TxtDir,'exp4_fn','cev_qo.txt'),[nq,2]);
exp5.cev_qo = 100*loadArray(fullfile(TxtDir,'exp5_fn','cev_qo.txt'),[nq,2]);
exp6.cev_qo = 100*loadArray(fullfile(TxtDir,'exp6_fn','cev_qo.txt'),[nq,2]);

exp1.cev_z = 100*loadArray(fullfile(TxtDir,'exp1_fn','cev_z.txt'),[4,1]);
exp2.cev_z = 100*loadArray(fullfile(TxtDir,'exp2_fn','cev_z.txt'),[4,1]);
exp3.cev_z = 100*loadArray(fullfile(TxtDir,'exp3_fn','cev_z.txt'),[4,1]);
exp4.cev_z = 100*loadArray(fullfile(TxtDir,'exp4_fn','cev_z.txt'),[4,1]);
exp5.cev_z = 100*loadArray(fullfile(TxtDir,'exp5_fn','cev_z.txt'),[4,1]);
exp6.cev_z = 100*loadArray(fullfile(TxtDir,'exp6_fn','cev_z.txt'),[4,1]);

% Load transition path from txt
exp2_tran = load_NoAvoidanceExp_tran(fullfile(TxtDir,'exp2_fn'));

% Load benchmark steady state result
ss_bench = load_comptran_ss(fullfile(TxtDir,'ss_bench'));

%% Plot CEV by percentile groups
figure
b=bar(exp1.cev_qo,mybw,'LineWidth',mybaredge);
b(1).FaceColor = myfc1;
b(2).FaceColor = myfc4;
ax = gca;
ax.FontSize = myfs; 
legend('Worker','Entrepreneur','fontsize',myfs,'location','best')
ylim([-2e0,ub])
xlabel('Wealth bins','fontsize',myfs)
ylabel('CEV (%)','fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'exp1_cev_qo'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'exp1_cev_qo'),'-depsc'); end

figure
b=bar(exp2.cev_qo,mybw,'LineWidth',mybaredge);
b(1).FaceColor = myfc1;
b(2).FaceColor = myfc4;
ax = gca;
ax.FontSize = myfs; 
legend('Worker','Entrepreneur','fontsize',myfs,'location','best')
ylim([-2e0,ub])
xlabel('Wealth bins','fontsize',myfs)
ylabel('CEV (%)','fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'exp2_cev_qo'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'exp2_cev_qo'),'-depsc'); end

figure
b=bar(exp3.cev_qo,mybw,'LineWidth',mybaredge);
b(1).FaceColor = myfc1;
b(2).FaceColor = myfc4;
ax = gca;
ax.FontSize = myfs; 
legend('Worker','Entrepreneur','fontsize',myfs,'location','best')
ylim([-2e0,ub])
xlabel('Wealth bins','fontsize',myfs)
ylabel('CEV (%)','fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'exp3_cev_qo'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'exp3_cev_qo'),'-depsc'); end

figure
b=bar(exp4.cev_qo,mybw,'LineWidth',mybaredge);
b(1).FaceColor = myfc1;
b(2).FaceColor = myfc4;
ax = gca;
ax.FontSize = myfs; 
legend('Worker','Entrepreneur','fontsize',myfs,'location','best')
ylim([-2e0,ub])
xlabel('Wealth bins','fontsize',myfs)
ylabel('CEV (%)','fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'exp4_cev_qo'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'exp4_cev_qo'),'-depsc'); end

%% CEV by occupation and legal form
% Exp 1-4
figure
X = categorical({'Worker','Sole-Prop.','S-Corp.','C-Corp.'});
X = reordercats(X,{'Worker','Sole-Prop.','S-Corp.','C-Corp.'});
b=bar(X',[exp1.cev_z,exp3.cev_z,exp2.cev_z,exp4.cev_z],mybw,'LineWidth',mybaredge);
b(1).FaceColor = myfc1;
b(2).FaceColor = myfc2;
b(3).FaceColor = myfc3;
b(4).FaceColor = myfc4;
ax = gca;
ax.FontSize = myfs; 
legend('Exp. 1','Exp. 2','Exp. 3','Exp. 4','fontsize',myfs,'location','southoutside','numcolumns',4)
%ylim([-2e0,ub])
%xlabel('Wealth decile','fontsize',myfs)
ylabel('CEV (%)','fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'cev_z'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'cev_z'),'-depsc'); end

% Experiments with no income shifting
figure
X = categorical({'Worker','Sole-Prop.','S-Corp.','C-Corp.'});
X = reordercats(X,{'Worker','Sole-Prop.','S-Corp.','C-Corp.'});
b=bar(X',[exp1.cev_z,exp3.cev_z],mybw,'LineWidth',mybaredge);
b(1).FaceColor = myfc1;
b(2).FaceColor = myfc2;
ax = gca;
ax.FontSize = myfs; 
legend('Exp. 1','Exp. 2','fontsize',myfs,'location','southoutside','numcolumns',4)
ylim([-3,5])
%xlabel('Wealth decile','fontsize',myfs)
ylabel('CEV (%)','fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'cev_z_exp1_2'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'cev_z_exp1_2'),'-depsc'); end


% Experiments with tax reform
figure
X = categorical({'Worker','Sole-Prop.','S-Corp.','C-Corp.'});
X = reordercats(X,{'Worker','Sole-Prop.','S-Corp.','C-Corp.'});
b=bar(X',[exp2.cev_z,exp4.cev_z],mybw,'LineWidth',mybaredge);
b(1).FaceColor = myfc3;
b(2).FaceColor = myfc4;
ax = gca;
ax.FontSize = myfs; 
legend('Exp. 3','Exp. 4','fontsize',myfs,'location','southoutside','numcolumns',4)
ylim([-3,5])
%xlabel('Wealth decile','fontsize',myfs)
ylabel('CEV (%)','fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'cev_z_exp3_4'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'cev_z_exp3_4'),'-depsc'); end

% Experiment with no-avoidance reform (exp 3 in paper only)
figure
X = categorical({'Worker','Sole-Prop.','S-Corp.','C-Corp.'});
X = reordercats(X,{'Worker','Sole-Prop.','S-Corp.','C-Corp.'});
b=bar(X',[exp2.cev_z]',0.3*mybw,'LineWidth',mybaredge);
b(1).FaceColor = myfc1;
%b(2).FaceColor = myfc4;
ax = gca;
ax.FontSize = myfs+1; 
%legend('Exp. ','fontsize',myfs,'location','southoutside','numcolumns',4)
ylim([0,6])
%xlabel('Wealth decile','fontsize',myfs)
ylabel('CEV (%)','fontsize',myfs+2)
if do_save==1; print(fullfile(FigDir,'cev_z_exp3'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'cev_z_exp3'),'-depsc'); end


% Experiments with lfo reform
figure
X = categorical({'Worker','Sole-Prop.','S-Corp.','C-Corp.'});
X = reordercats(X,{'Worker','Sole-Prop.','S-Corp.','C-Corp.'});
b=bar(X',[exp5.cev_z]',0.3*mybw,'LineWidth',mybaredge);
b(1).FaceColor = myfc3;
%b(2).FaceColor = myfc4;
ax = gca;
ax.FontSize = myfs; 
legend('Exp. 5','fontsize',myfs,'location','southoutside','numcolumns',4)
ylim([-3,5])
%xlabel('Wealth decile','fontsize',myfs)
ylabel('CEV (%)','fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'cev_z_exp5'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'cev_z_exp5'),'-depsc'); end


% Experiments with tax reform
figure
X = categorical({'Worker','Sole-Prop.','S-Corp.','C-Corp.'});
X = reordercats(X,{'Worker','Sole-Prop.','S-Corp.','C-Corp.'});
b=bar(X',[exp2.cev_z,exp5.cev_z],mybw,'LineWidth',mybaredge-1);
b(1).FaceColor = myfc1;
b(2).FaceColor = myfc3;
ax = gca;
ax.FontSize = myfs; 
legend('Equal Tax Treatment','Sole-Prop. Only','fontsize',myfs,'location','southoutside','numcolumns',4)
ylim([-3.5,5])
%xlabel('Wealth decile','fontsize',myfs)
ylabel('CEV (%)','fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'cev_z_exp_taxreform'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'cev_z_exp_taxreform'),'-depsc'); end

%% Figure: Transition paths to experiment economy

T = size(exp2_tran.r,1); % total number of periods on transition path
Tmax = (T*40/100);
tvec = (0:Tmax)';


% experiment 2: tax reform (i.e. exp 3 in the paper)

% interest rate and wage
figure
plot(tvec,100*[0,exp2_tran.r(1:Tmax)'-ss_bench.r],mylp1,'LineWidth',mylw,'Color',mylc1)
hold on
ylabel('Interest rate (p.p. change)','fontsize',myfs)
yyaxis right
plot(tvec,100*[0,(exp2_tran.w(1:Tmax)'-ss_bench.w)/ss_bench.w],mylp2,'LineWidth',mylw,'Color',mylc2)
hold on
ylabel('Wage (% change)','fontsize',myfs,'Color','k')
ax = gca;
ax.FontSize = myfs;
ax.YAxis(2).Color = 'k';
xlabel('Years','fontsize',myfs)
legend('Interest rate','Wage','fontsize',myfs,'location','best','numColumns',2)
if do_save==1; print(fullfile(FigDir,'exp2_tran_r_w'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'exp2_tran_r_w'),'-depsc'); end

% Aggregate output, capital
figure
plot(tvec,100*[0,(exp2_tran.Y(1:Tmax)'-ss_bench.Y)/ss_bench.Y],mylp1,'LineWidth',mylw,'Color',mylc1)
hold on
plot(tvec,100*[0,(exp2_tran.K(1:Tmax)'-ss_bench.K)/ss_bench.K],mylp2,'LineWidth',mylw,'Color',mylc2)
hold on
ylabel('% change','fontsize',myfs)
ax = gca;
ax.FontSize = myfs;
xlabel('Years','fontsize',myfs)
legend('Agg. output','Agg. capital','fontsize',myfs,'location','best','numColumns',2)
if do_save==1; print(fullfile(FigDir,'exp2_tran_Y_K'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'exp2_tran_Y_K'),'-depsc'); end

% ave entre capital, entre share of output
exp2_tran.Y_entre_share = exp2_tran.Y_entre./exp2_tran.Y;
ss_bench.Y_entre_share = ss_bench.Y_entre/ss_bench.Y;
figure
plot(tvec,100*[0,(exp2_tran.avek(1:Tmax,1)'-ss_bench.agg_avek_allentre)/ss_bench.agg_avek_allentre],mylp1,'LineWidth',mylw,'Color',mylc1)
hold on
ylabel('Ave. entre. capital (% change)','fontsize',myfs)
yyaxis right
plot(tvec,100*[0,exp2_tran.Y_entre_share(1:Tmax)'-ss_bench.Y_entre_share],mylp2,'LineWidth',mylw,'Color',mylc2)
hold on
ylabel('Entre. share of output (p.p. change)','fontsize',myfs,'Color','k')
ax = gca;
ax.FontSize = myfs;
ax.YAxis(2).Color = 'k';
xlabel('Years','fontsize',myfs)
legend('Ave. entre. capital','Entre. share of output','fontsize',myfs,'location','best','numColumns',2)
if do_save==1; print(fullfile(FigDir,'exp2_tran_avek_Y_entre'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'exp2_tran_avek_Y_entre'),'-depsc'); end

% Total tax revenue (excl. ss), S.S. tax rev., tau_p
exp2_tran.taxes_inc_corp_div = exp2_tran.taxes_inc+exp2_tran.taxes_corp+exp2_tran.taxes_div;
ss_bench.taxes_inc_corp_div = ss_bench.taxes_inc+ss_bench.taxes_corp+ss_bench.taxes_div;
figure
plot(tvec,100*[0,(exp2_tran.taxes_inc_corp_div(1:Tmax,1)'-ss_bench.taxes_inc_corp_div)/ss_bench.taxes_inc_corp_div],mylp1,'LineWidth',mylw,'Color',mylc1)
hold on
plot(tvec,100*[0,(exp2_tran.taxes_ss(1:Tmax,1)'-ss_bench.taxes_ss)/ss_bench.taxes_ss],mylp2,'LineWidth',mylw,'Color',mylc2)
hold on
ylabel('Tax revenue (% change)','fontsize',myfs)
yyaxis right
plot(tvec,100*[0,exp2_tran.tau_p(1:Tmax)'-ss_bench.tau_p],mylp3,'LineWidth',mylw,'Color',mylc3)
hold on
ylabel('Social security tax rate (p.p. change)','fontsize',myfs,'Color','k')
legend('Total revenue (excl. soc. sec.)','Soc. sec. revenue','Soc. sec. rate', ...
    'fontsize',myfs,'location','northwest','numColumns',1)
ax = gca;
ax.FontSize = myfs;
ax.YAxis(2).Color = 'k';
xlabel('Years','fontsize',myfs)
if do_save==1; print(fullfile(FigDir,'exp2_tran_taxes'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'exp2_tran_taxes'),'-depsc'); end

% Share of entre and lfo 
figure
plot(tvec,100*[0,exp2_tran.share_entre(1:Tmax,1)'-ss_bench.share_entre],mylp1,'LineWidth',mylw,'Color',mylc1)
hold on
plot(tvec,100*[0,exp2_tran.share_entre(1:Tmax,2)'-ss_bench.share_ep],mylp2,'LineWidth',mylw,'Color',mylc2)
hold on
plot(tvec,100*[0,exp2_tran.share_entre(1:Tmax,4)'-ss_bench.share_ec],mylp3,'LineWidth',mylw,'Color',mylc3)
hold on
ylabel('Share (p.p. change)','fontsize',myfs)
ax = gca;
ax.FontSize = myfs;
ax.YLim=[-40,70];
xlabel('Years','fontsize',myfs)
legend('Share of entre.','Sole prop. as share of entre.','C-corp. as share of entre.', ...
    'fontsize',myfs,'location','east','numColumns',1)
if do_save==1; print(fullfile(FigDir,'exp2_tran_share_entre'),'-dpng'); end
if do_save==1; print(fullfile(FigDir,'exp2_tran_share_entre'),'-depsc'); end

